### ISSUE TITLE
Hej, är nyfiken på att testa detta på min atlas, är ny inom detta och är lite nyfiken på hur jag enklast lägger in detta i HA?

### ISSUE THREAD

**Issue by ejansson88** [gustavstrandberg/ThermiaGenesisSmartControl#1]

**Comment by gustavstrandberg** [comment]
Jag kan guida dig över teams någon dag om du vill.

**Comment by ejansson88** [comment]
Det skulle vara mycket uppskattat, vad har du för mailadress så kan vi styra upp en tid som passar?

**Comment by gustavstrandberg** [comment]
maila mitt förnamn.efternamn (a) vgregion.se så styr vi upp det
